USE [master]
GO

/****** Object:  Database [simplePA]    Script Date: 2022-12-12 오전 11:16:44 ******/
CREATE DATABASE [simplePA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'simplePA', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\simplePA.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'simplePA_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\simplePA_log.ldf' , SIZE = 1280KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [simplePA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [simplePA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [simplePA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [simplePA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [simplePA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [simplePA] SET ARITHABORT OFF 
GO

ALTER DATABASE [simplePA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [simplePA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [simplePA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [simplePA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [simplePA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [simplePA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [simplePA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [simplePA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [simplePA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [simplePA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [simplePA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [simplePA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [simplePA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [simplePA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [simplePA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [simplePA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [simplePA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [simplePA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [simplePA] SET  MULTI_USER 
GO

ALTER DATABASE [simplePA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [simplePA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [simplePA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [simplePA] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [simplePA] SET  READ_WRITE 
GO


