//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetBases
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AssetBases()
        {
            this.ch = 0;
        }
    
        public long AssetBaseId { get; set; }
        public string id { get; set; }
        public string logicid { get; set; }
        public string ip { get; set; }
        public string GroupName { get; set; }
        public string ZoneName { get; set; }
        public string SpeakerName { get; set; }
        public string path { get; set; }
        public string floor { get; set; }
        public string DeviceName { get; set; }
        public string state { get; set; }
        public string state_old { get; set; }
        public long chk { get; set; }
        public long seq { get; set; }
        public long AssetGroupId { get; set; }
        public Nullable<System.DateTime> wtime { get; set; }
        public int ch { get; set; }
    
        public virtual AssetGroups AssetGroups { get; set; }
    }
}
