//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Floorbases
    {
        public long FloorBaseId { get; set; }
        public string Id { get; set; }
        public string logicid { get; set; }
        public string buildingname { get; set; }
        public long floororder { get; set; }
        public string floor { get; set; }
        public string filename { get; set; }
        public double left { get; set; }
        public double top { get; set; }
        public string content { get; set; }
        public string assetname { get; set; }
    }
}
