//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holidays
    {
        public long HolidayId { get; set; }
        public string id { get; set; }
        public System.DateTime hDate { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public Nullable<long> SimplePAId { get; set; }
    
        public virtual Simplepa Simplepa { get; set; }
    }
}
