//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimpleMultis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SimpleMultis()
        {
            this.Musics = new HashSet<Musics>();
        }
    
        public long SimpleMultiId { get; set; }
        public string Id { get; set; }
        public long idno { get; set; }
        public long chno { get; set; }
        public string Subject { get; set; }
        public string Name { get; set; }
        public Nullable<long> gstreeAssetGroupId { get; set; }
        public string stm { get; set; }
        public string etm { get; set; }
        public string duration { get; set; }
        public long week { get; set; }
        public long day1 { get; set; }
        public long day2 { get; set; }
        public long day3 { get; set; }
        public long day4 { get; set; }
        public long day5 { get; set; }
        public long day6 { get; set; }
        public long day7 { get; set; }
        public string tss { get; set; }
        public string tse { get; set; }
        public string Color16 { get; set; }
        public long overlap { get; set; }
        public long weekday { get; set; }
    
        public virtual AssetGroups AssetGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Musics> Musics { get; set; }
    }
}
