//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simplepa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Simplepa()
        {
            this.Holidays = new HashSet<Holidays>();
            this.UserTrees = new HashSet<UserTrees>();
        }
    
        public long SimplePAId { get; set; }
        public long TileWidth { get; set; }
        public long MapX { get; set; }
        public long MapY { get; set; }
        public double Zoom { get; set; }
        public long debug { get; set; }
        public long SpeakerIconSize { get; set; }
        public string UserName { get; set; }
        public string EMServerIP { get; set; }
        public string ServerIP { get; set; }
        public string ServerPort { get; set; }
        public string Reserved1 { get; set; }
        public string Reserved2 { get; set; }
        public string Reserved3 { get; set; }
        public string Reserved4 { get; set; }
        public string Reserved5 { get; set; }
        public string Reserved6 { get; set; }
        public string Reserved7 { get; set; }
        public string Reserved8 { get; set; }
        public string Reserved9 { get; set; }
        public string Reserved10 { get; set; }
        public string Reserved11 { get; set; }
        public string GPIOPort { get; set; }
        public string Rport { get; set; }
        public string Reserved14 { get; set; }
        public string Reserved15 { get; set; }
        public string Reserved16 { get; set; }
        public long Jigsangbalhwa { get; set; }
        public long SpeakerTimer { get; set; }
        public double inputvolume { get; set; }
        public double outputvolume { get; set; }
        public long disp { get; set; }
        public long Multi_Ch { get; set; }
        public long SoundDeviceNum { get; set; }
        public string SoundDeviceName { get; set; }
        public long Reserved17 { get; set; }
        public double scalelength { get; set; }
        public double length { get; set; }
        public double scale { get; set; }
        public long noise1 { get; set; }
        public long noise2 { get; set; }
        public long dsp_vol { get; set; }
        public long dsp_vol_em { get; set; }
        public string sms_server { get; set; }
        public string sms_id { get; set; }
        public string sms_pw { get; set; }
        public string sms_rcvno { get; set; }
        public long Pport { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Holidays> Holidays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserTrees> UserTrees { get; set; }
    }
}
