//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simplepa2.Controller
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assets
    {
        public int AssetId { get; set; }
        public string emServer { get; set; }
        public string ip { get; set; }
        public string GroupName { get; set; }
        public string ZoneName { get; set; }
        public string SpeakerName { get; set; }
        public string path { get; set; }
        public Nullable<int> floor { get; set; }
        public string DeviceName { get; set; }
        public string state { get; set; }
        public string state_old { get; set; }
        public Nullable<int> chk { get; set; }
        public Nullable<int> seq { get; set; }
        public Nullable<int> ch { get; set; }
        public Nullable<int> em1 { get; set; }
        public Nullable<int> em2 { get; set; }
        public Nullable<int> em3 { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public string emData { get; set; }
        public string building { get; set; }
        public string floorname { get; set; }
        public string zpc { get; set; }
        public Nullable<int> zpci { get; set; }
        public Nullable<int> zpco { get; set; }
    }
}
