//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simplepa2.Controller
{
    using System;
    using System.Collections.Generic;
    
    public partial class Device
    {
        public int DeviceId { get; set; }
        public Nullable<int> device { get; set; }
        public string ip { get; set; }
        public string ip_dspctrl { get; set; }
        public string name { get; set; }
        public string DeviceName { get; set; }
        public string DanteModelName { get; set; }
        public Nullable<int> chspk { get; set; }
        public string dsp_name { get; set; }
        public Nullable<int> dsp_chno { get; set; }
        public Nullable<int> dsp_vol { get; set; }
        public Nullable<int> dsp_vol_em { get; set; }
        public string path { get; set; }
        public Nullable<int> floor_em { get; set; }
        public string emData { get; set; }
        public Nullable<int> chCount { get; set; }
        public Nullable<int> AssetId { get; set; }
    }
}
