//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simplepa2.Controller
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceChannel
    {
        public int DeviceChnnelId { get; set; }
        public string chno { get; set; }
        public string chname { get; set; }
        public string dsp_out_ch1 { get; set; }
        public string dsp_out_ch2 { get; set; }
        public int DeviceId { get; set; }
        public Nullable<int> io { get; set; }
        public string devicein { get; set; }
        public Nullable<int> deviceinch { get; set; }
    }
}
