//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simplepa2.Controller
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class simplePAEntities : DbContext
    {
        public simplePAEntities()
            : base("name=simplePAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AssetGroups> AssetGroups { get; set; }
        public virtual DbSet<Assets> Assets { get; set; }
        public virtual DbSet<BSroom> BSroom { get; set; }
        public virtual DbSet<BSTree> BSTree { get; set; }
        public virtual DbSet<Device> Device { get; set; }
        public virtual DbSet<DeviceChannel> DeviceChannel { get; set; }
        public virtual DbSet<EMServer> EMServer { get; set; }
        public virtual DbSet<Eventvm> Eventvm { get; set; }
        public virtual DbSet<Musics> Musics { get; set; }
        public virtual DbSet<UserTrees> UserTrees { get; set; }
        public virtual DbSet<PlayItem> PlayItem { get; set; }
        public virtual DbSet<BSTreeC> BSTreeC { get; set; }
        public virtual DbSet<AssetPresetGroups> AssetPresetGroups { get; set; }
        public virtual DbSet<spa_bd_struct> spa_bd_struct { get; set; }
        public virtual DbSet<spa_site> spa_site { get; set; }
        public virtual DbSet<Simplepa> Simplepa { get; set; }
        public virtual DbSet<Eventbs> Eventbs { get; set; }
        public virtual DbSet<Eventdevice> Eventdevice { get; set; }
        public virtual DbSet<Eventpreset> Eventpreset { get; set; }
        public virtual DbSet<Eventsyslog> Eventsyslog { get; set; }
        public virtual DbSet<Holidays> Holidays { get; set; }
        public virtual DbSet<TypeData> TypeData { get; set; }
        public virtual DbSet<EMBs> EMBs { get; set; }
    }
}
