//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simplepa2.Controller
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schdule
    {
        public int SchduleId { get; set; }
        public string Name { get; set; }
        public string EMNAME { get; set; }
        public string GroupName { get; set; }
        public string user_name { get; set; }
        public System.DateTime stime { get; set; }
        public System.DateTime etime { get; set; }
        public System.DateTime sdate { get; set; }
        public bool day1 { get; set; }
        public bool day2 { get; set; }
        public bool day3 { get; set; }
        public bool day4 { get; set; }
        public bool day5 { get; set; }
        public bool day6 { get; set; }
        public bool day7 { get; set; }
        public bool week { get; set; }
        public int chno { get; set; }
        public string duration { get; set; }
        public string tss { get; set; }
        public string tse { get; set; }
    }
}
