//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simplepa2.Controller
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_site
    {
        public int site_index { get; set; }
        public string site_name { get; set; }
        public string site_description { get; set; }
        public Nullable<int> num_of_bd { get; set; }
        public Nullable<int> em_device_id { get; set; }
        public string site_address { get; set; }
        public string site_contact { get; set; }
        public string site_images { get; set; }
        public Nullable<bool> is_deleted { get; set; }
    }
}
