//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simplepa2.Controller
{
    using System;
    using System.Collections.Generic;
    
    public partial class spa_bd_struct
    {
        public int bd_id { get; set; }
        public string bd_name { get; set; }
        public int refer_site_id { get; set; }
        public Nullable<int> max_floor_no { get; set; }
        public Nullable<int> under_floor_no { get; set; }
        public Nullable<int> num_of_stairs { get; set; }
        public Nullable<int> bd_fire_id { get; set; }
        public string bd_description { get; set; }
    }
}
